# Generated by Django 2.0.7 on 2018-08-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(blank=True, to='categories.Category')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
