# Generated by Django 2.1.3 on 2018-11-20 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20181120_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmark.Bookmark'),
        ),
    ]
